apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: LoadBalancer
  selector:
    app: pythonapp   # Must match labels in your deployment pods
  ports:
    - protocol: TCP
      port: 80       # The port users access via ELB
      targetPort: 8001  # The port your container listens on
